### ISSUE TITLE
Clean up code structure

### ISSUE THREAD

**Issue by smcclure20** [paraglider-project/paraglider#203]
Per discussion with @seankimkdy. Here are some of my initial suggestions. Feel free to add more / suggest edits.

- [x] Put helper functions in category-based files (ex. all helper functions for naming conventions in one file) [applies to all plugins] 
    - [x] Azure: #243 
    - [x] GCP: #253 
- [x] Rename azure_plugin to azure [#243]
- [x] Remove the AzureSDKHandler as an interface for tests that must be mocked [#250 ]
- [ ] #364
- [ ] #365
- [x] #236
- [x] Migrate all documentation files to docs from top-level README (contributing, etc) [#233 ]
- [ ] (Lower-priority) Add logging [#84 ]

**Comment by divega** [comment]
Triage: Closing as we have broken up into individual issues.
