### ISSUE TITLE
Follow up tasks for project rename

### ISSUE THREAD

**Issue by divega** [paraglider-project/paraglider#208]
In a somewhat strict order of precedence:
- [x] Rename repo. [@seankimkdy]
- [x] Search and replace old name with "paraglider" in code and docs. [#251 ]
- [x] #226
- [x] Update GitHub actions usage. [@seankimkdy] (#209)
- [x] Update package publishing. [#251]

@seankimkdy, @smcclure20, anything else that I might be missing?
