### ISSUE TITLE
LF Pre-Release Tasks 

### ISSUE THREAD

**Issue by smcclure20** [paraglider-project/paraglider#215]
- [x] Add the DNS record to point to the GH pages
- [x] Add the DCO bot to the repo
- [x] Add the technical charter to the repo [#233 ]
- [x] Add the following footer to the website: [#216]
        Copyright © Paraglider a Series of LF Projects, LLC
        For web site terms of use, trademark policy and other project policies please see https://lfprojects.org/.
- [x] Add the long-form mission statement and other general project descriptions to the website [#219 ]
- [x] Make the repo public
- [x] Make the GH pages site public
- [x] #220
