### ISSUE TITLE
Other Pre-Release Tasks

### ISSUE THREAD

**Issue by smcclure20** [paraglider-project/paraglider#221]
- [x] Add known issues to docs (ex. that IBM rules are weird right now) [#222]
- [x] Add a roadmap to the docs[#222]
- [x] Update the contributors guide (info about integration tests)
- [ ] Set up a dev branch
- [ ] Add a release binary [noted as beta]
- [x] Add developer docs for meeting the plugin interface [#231 ]
- [x] Add to the roadmap: async and network functions [#233 ]
- [x] Update the API reference doc [#240]
- [x] Update the design doc [#240]
